-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
    [1] = {"@Dilapitaded Dungeon/Dream Breaker/"},
    [2] = {"@Dilapitaded Dungeon/Slide/"},
    [3] = {"@Dilapitaded Dungeon/Alcove Near Mirror/"},
    [4] = {"@Dilapitaded Dungeon/Dark Orbs/"},
    [5] = {"@Dilapitaded Dungeon/Past Poles/"},
    [6] = {"@Dilapitaded Dungeon/Rafters/"},
    [7] = {"@Dilapitaded Dungeon/Strong Eyes/"},

    [8] = {"@Castle Sansa/Indignation/"},
    [9] = {"@Castle Sansa/Alcove Near Dungeon/"},
    [10] = {"@Castle Sansa/Balcony/"},
    [11] = {"@Castle Sansa/Corner Corridor/"},
    [12] = {"@Castle Sansa/Floater In Courtyard/"},
    [14] = {"@Castle Sansa/Platform In Main Halls/"},
    [15] = {"@Castle Sansa/Tall Room Near Wheel Crawlers/"},
    [16] = {"@Castle Sansa/Wheel Crawlers/"},
    [17] = {"@Upper Castle Sansa/High Climb From Courtyard/"},
    [18] = {"@Upper Castle Sansa/Alcove Near Scythe Corridor/"},
    [19] = {"@Upper Castle Sansa/Near Theatre Front/"},

    [20] = {"@Sansa Keep/Strikebreak/"},
    [21] = {"@Sansa Keep/Alcove Near Locked Door/"},
    [22] = {"@Sansa Keep/Levers Room/"},
    [23] = {"@Sansa Keep/Lonely Throne/"},
    [24] = {"@Sansa Keep/Near Theatre/"},
    [25] = {"@Sansa Keep/Sunsetter/"},

    [26] = {"@Listless Library/Sun Greaves/"},
    [27] = {"@Listless Library/Upper Back/"},
    [28] = {"@Listless Library/Locked Door Across/"},
    [29] = {"@Listless Library/Locked Door Left/"},

    [30] = {"@Twilight Theatre/Soul Cutter/"},
    [31] = {"@Twilight Theatre/Back Of Auditorium/"},
    [32] = {"@Twilight Theatre/Center Stage/"},
    [33] = {"@Twilight Theatre/Locked Door/"},
    [34] = {"@Twilight Theatre/Tucked Behind Boxes/"},
    [35] = {"@Twilight Theatre/Corner Beam/"},

    [36] = {"@Empty Bailey/Solar Wind/"},
    [37] = {"@Empty Bailey/Center Steeple/"},
    [38] = {"@Empty Bailey/Cheese Bell/"},
    [39] = {"@Empty Bailey/Guarded Hand/"},
    [40] = {"@Empty Bailey/Inside Building/"},

    [41] = {"@Underbelly/Ascendant Light/"},
    [42] = {"@Underbelly/Alcove Near Light/"},
    [43] = {"@Underbelly/Building Near Little Guy/"},
    [44] = {"@Underbelly/Locked Door/"},
    [45] = {"@Underbelly/Main Room/"},
    [46] = {"@Underbelly/Rafters Near Keep/"},
    [47] = {"@Underbelly/Strikebreak Wall/"},
    [48] = {"@Underbelly/Surrounded By Holes/"},

    [49] = {"@Tower Remains/Cling Gem/"},
    [50] = {"@Tower Remains/Atop The Tower/"},

    [51] = {"@Listless Library/Sun Greaves Split/"},
    [52] = {"@Listless Library/Sun Greaves Split/"},
    [53] = {"@Listless Library/Sun Greaves Split/"},

    [54] = {"@Dilapitaded Dungeon/Time Trial/"},
    [55] = {"@Castle Sansa/Time Trial/"},
    [56] = {"@Sansa Keep/Time Trial/"},
    [57] = {"@Listless Library/Time Trial/"},
    [58] = {"@Twilight Theatre/Time Trial/"},
    [59] = {"@Empty Bailey/Time Trial/"},
    [60] = {"@Underbelly/Time Trial/"},
    [61] = {"@Tower Remains/Time Trial/"},

    [62] = {"@Castle Sansa/Memento/"},

    [63] = {"@Tower Remains/Cling Gem Split/"},
    [64] = {"@Tower Remains/Cling Gem Split/"},
    [65] = {"@Tower Remains/Cling Gem Split/"},

    [66] = {"@Dilapitaded Dungeon/Mirror Room Goatling/"},
    [67] = {"@Dilapitaded Dungeon/Rambling Goatling/"},
    [68] = {"@Dilapitaded Dungeon/Unwelcoming Goatling/"},
    [69] = {"@Dilapitaded Dungeon/Repentant Goatling/"},
    [70] = {"@Dilapitaded Dungeon/Defeatist Goatling/"},
    [71] = {"@Castle Sansa/Crystal Licker Goatling/"},
    [72] = {"@Castle Sansa/Gazebo Goatling/"},
    [73] = {"@Castle Sansa/Bubblephobic Goatling/"},
    [74] = {"@Upper Castle Sansa/Trapped Goatling/"},
    [75] = {"@Castle Sansa/Memento Goatling/"},
    [76] = {"@Castle Sansa/Goatling Near Library/"},
    [77] = {"@Sansa Keep/Furniture-less Goatling/"},
    [78] = {"@Sansa Keep/Distorted Goatling/"},
    [79] = {"@Twilight Theatre/20 Bean Casserole Goatling/"},
    [80] = {"@Twilight Theatre/Theatre Goer Goatling 1/"},
    [81] = {"@Twilight Theatre/Theatre Goer Goatling 2/"},
    [82] = {"@Twilight Theatre/Theatre Manager Goatling/"},
    [83] = {"@Twilight Theatre/Murderous Goatling/"},
    [84] = {"@Empty Bailey/Alley Goatling/"},

    [85] = {"@Castle Sansa/Stool Near Crystal/"},
    [86] = {"@Castle Sansa/Stool Near Crystal/"},
    [87] = {"@Castle Sansa/Stool Near Crystal/"},
    [88] = {"@Castle Sansa/Gazebo Stool/"},
    [89] = {"@Sansa Keep/Distorted Stool/"},
    [90] = {"@Sansa Keep/Path to Throne Stool/"},
    [91] = {"@Sansa Keep/The Throne/"},
    [92] = {"@Listless Library/Hay Bale Near Entrance/"},
    [93] = {"@Listless Library/Hay Bale Near Eggs/"},
    [94] = {"@Listless Library/Hay Bale in the Back/"},
    [95] = {"@Twilight Theatre/Stool Near Bookcase/"},
    [96] = {"@Twilight Theatre/Stool Around a Table/"},
    [97] = {"@Twilight Theatre/Stool Around a Table/"},
    [98] = {"@Twilight Theatre/Stool Around a Table/"},
    [99] = {"@Twilight Theatre/Stage Left Stool/"},
    [100] = {"@Twilight Theatre/Stage Right Stool/"},

    [101] = {"@Listless Library/A Book About a Princess/"},
    [102] = {"@Listless Library/A Book About Cooking/"},
    [103] = {"@Listless Library/A Book Full of Plays/"},
    [104] = {"@Listless Library/A Book About Reading/"},
    [105] = {"@Listless Library/A Book About Aquatic Life/"},
    [106] = {"@Listless Library/A Book About a Jester/"},
    [107] = {"@Listless Library/A Book About Loss/"},
    [108] = {"@Listless Library/A Book on Musical Theory/"},
    [109] = {"@Listless Library/A Book About a Girl/"},
    [110] = {"@Listless Library/A Book About a Thimble/"},
    [111] = {"@Listless Library/A Book About a Monster/"},
    [112] = {"@Listless Library/A Book About Revenge/"},
    [113] = {"@Listless Library/A Book About a Restaurant/"},

    [114] = {"@Listless Library/Note Near Eggs/"},
    [115] = {"@Underbelly/Note on a Ledge/"},
    [116] = {"@Underbelly/Note in the Big Room/"},
    [117] = {"@Underbelly/Note Behind a Locked Door/"},
}
