constants = {
    difficulties = {
        ["NORMAL"] = 1,
        ["HARD"] = 2,
        ["EXPERT"] = 3,
        ["LUNATIC"] = 4,
    },
    versions = {
        ["MAP_PATCH"] = 1,
        ["FULL_GOLD"] = 2,
    },
    playerStarts = {
        ["DungeonMirror"] = 0,
        ["DungeonMirrorSave"] = 1,
        ["DungeonSlideSave"] = 2,
        ["DungeonStrongEyesSave"] = 3,
        ["DungeonStrongEyesExit"] = 4,
        ["DungeonEscapeLowerExit"] = 5,
        ["DungeonEscapeUpperExit"] = 6,

        ["CastleWestSave"] = 7,
        ["CastleGazeboSave"] = 8,
        ["CastleEastSave"] = 9,
        ["CastleNorthwestSave"] = 10,
        ["CastleWestLowerExit"] = 11,
        ["CastleWestUpperExit"] = 12,
        ["CastleSouthLowerExit"] = 13,
        ["CastleSouthUpperExit"] = 14,
        ["CastleLockedExit"] = 15,
        ["CastleEastExit"] = 16,
        ["CastleNorthExit"] = 17,
        ["CastleNorthwestExit"] = 18,

        ["KeepCentralSave"] = 19,
        ["KeepNorthSave"] = 20,
        ["KeepSouthExit"] = 21,
        ["KeepSouthwestExit"] = 22,
        ["KeepLockedExit"] = 23,
        ["KeepNortheastExit"] = 24,
        ["KeepNorthExit"] = 25,

        ["LibraryMainSave"] = 26,
        ["LibraryBackSave"] = 27,
        ["LibraryExit"] = 28,

        ["TheatreSave"] = 29,
        ["TheatrePillarWestExit"] = 30,
        ["TheatrePillarEastExit"] = 31,
        ["TheatreFrontExit"] = 32,
        ["TheatreScythesNorthExit"] = 33,
        ["TheatreScythesSouthExit"] = 34,

        ["BaileySave"] = 35,
        ["BaileyNorthExit"] = 36,
        ["BaileyWestExit"] = 37,
        ["BaileyShackExit"] = 38,
        ["BaileyEastExit"] = 39,

        ["UnderbellySouthSave"] = 40,
        ["UnderbellyCentralSave"] = 41,
        ["UnderbellyEastSave"] = 42,
        ["UnderbellyPreLightSave"] = 43,
        ["UnderbellyPostLightSave"] = 44,
        ["UnderbellySouthExit"] = 45,
        ["UnderbellyHoleExit"] = 46,
        ["UnderbellyLightPillarExit"] = 47,

        ["TowerSave"] = 48,
        ["TowerSouthExit"] = 49,
        ["TowerTopExit"] = 50,

        ["ChambersExit"] = 51,
    },
}
return constants
